import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { engineInfo } from "../src/sim/engine";
import { PARAM_SPEC } from "../src/sim/params";
import {
  CALIBRATION,
  MODEL_CONSTANTS,
  REVISION_LOG,
  SECTION_IDS,
  applyGenerated,
  beginMarker,
  endMarker,
  formatDefault,
  identityFacts,
  renderSection,
} from "../tools/modeldoc";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const docPath = resolve(root, "docs/model.md");
const baselinePath = resolve(root, "tests/baselines/engine.json");

interface Baseline {
  version: string;
  revision: number;
  perfHash: string;
}

function readDoc(): string {
  return readFileSync(docPath, "utf8");
}

function baseline(): Baseline {
  return JSON.parse(readFileSync(baselinePath, "utf8")) as Baseline;
}

/** Body of one generated block, without the markers. */
function block(doc: string, id: (typeof SECTION_IDS)[number]): string {
  const begin = beginMarker(id);
  const end = endMarker(id);
  const b = doc.indexOf(begin);
  const e = doc.indexOf(end);
  expect(b, `${id} block missing`).toBeGreaterThanOrEqual(0);
  return doc.slice(b + begin.length, e);
}

describe("docs/model.md stays in sync with the model", () => {
  it("is regenerated by npm run docs and otherwise reproduces byte for byte", () => {
    const doc = readDoc();
    const next = applyGenerated(doc);
    if (process.env.OPENAVIDA_UPDATE_DOC === "1") {
      writeFileSync(docPath, next);
      return;
    }
    expect(
      next,
      "docs/model.md is stale: run npm run docs",
    ).toBe(doc);
    expect(next).toBe(applyGenerated(next));
  });

  it("documents every parameter exactly once, inside the parameters block", () => {
    const body = block(readDoc(), "params");
    for (const spec of PARAM_SPEC) {
      const marker = `\`${spec.key}\``;
      const n = body.split(marker).length - 1;
      expect(n, `${spec.key} should appear once in the parameter table`).toBeGreaterThanOrEqual(1);
    }
    expect(PARAM_SPEC.length).toBeGreaterThan(30);
  });

  it("keeps every marker unique and paired, and refuses unknown blocks", () => {
    const doc = readDoc();
    for (const id of SECTION_IDS) {
      expect(doc.split(beginMarker(id)).length - 1, `${id} begin`).toBe(1);
      expect(doc.split(endMarker(id)).length - 1, `${id} end`).toBe(1);
      expect(doc.indexOf(beginMarker(id))).toBeLessThan(doc.indexOf(endMarker(id)));
      expect(renderSection(id).trim().length, `${id} renders something`).toBeGreaterThan(0);
    }
    expect(() => applyGenerated(`${doc}\n<!-- generated:nonsense -->\n`)).toThrow(/unknown generated block/);
    expect(() => applyGenerated(doc.replace(beginMarker("params"), ""))).toThrow(/missing the "params" block/);
  });

  it("pins the current revision against the engine identity and the baseline file", () => {
    const last = REVISION_LOG.at(-1)!;
    expect(last.version).toBe(engineInfo().version);
    expect(last.revision).toBe(engineInfo().revision);
    expect(last.perfHash).toBe(baseline().perfHash);
    expect(identityFacts()).toEqual({
      version: engineInfo().version,
      revision: engineInfo().revision,
      hashAlgo: engineInfo().hashAlgo,
    });
    // Older rows are the recorded history: versions must descend, hashes be distinct.
    expect(new Set(REVISION_LOG.map((r) => r.perfHash)).size).toBe(REVISION_LOG.length);
    for (let i = 1; i < REVISION_LOG.length; i++) {
      expect(REVISION_LOG[i]!.revision).toBe(REVISION_LOG[i - 1]!.revision + 1);
    }
  });

  it("reads every documented constant from the file it names", () => {
    for (const entry of MODEL_CONSTANTS) {
      const source = resolve(root, entry.source);
      expect(existsSync(source), `${entry.source} exists`).toBe(true);
      const text = readFileSync(source, "utf8");
      for (const name of entry.names ?? [entry.name]) {
        expect(text, `${entry.source} defines ${name}`).toContain(`const ${name}`);
      }
      expect(entry.note.length, entry.name).toBeGreaterThan(10);
      expect(entry.value.length, entry.name).toBeGreaterThan(0);
    }
  });

  it("points every checked calibration claim at a test that carries its marker", () => {
    const checked = CALIBRATION.filter((c) => c.check.kind === "test");
    expect(checked.length).toBeGreaterThanOrEqual(5);
    for (const entry of CALIBRATION) {
      for (const field of [entry.claim, entry.method, entry.measured, entry.tolerance, entry.source]) {
        expect(field.trim().length, entry.id).toBeGreaterThan(10);
      }
      if (entry.check.kind !== "test") continue;
      const file = resolve(root, entry.check.file);
      expect(existsSync(file), `${entry.check.file} exists`).toBe(true);
      expect(readFileSync(file, "utf8"), `${entry.check.file} marks ${entry.id}`).toContain(
        `calibration:${entry.id}`,
      );
    }
  });

  it("formats awkward defaults without losing the exact value", () => {
    const drought = PARAM_SPEC.find((s) => s.key === "droughtRate")!;
    expect(formatDefault(drought.default)).toBe("0.011363636363636364 (1/88)");
    expect(formatDefault(PARAM_SPEC.find((s) => s.key === "maxMealsPerTick")!.default)).toBe("1");
    expect(formatDefault(PARAM_SPEC.find((s) => s.key === "diffusionRate")!.default)).toBe("0.22");
    expect(formatDefault(true)).toBe("true");
    expect(formatDefault(0)).toBe("0");
  });
});
